//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROCJUD.Repositorio
{
     
    using PROCJUD.Entidades;
    using PROCJUD.IRepositorio;
    using PROCJUD.IRepositorio.Base;
    using PROCJUD.Repositorio.Base;
    using System;
    using System.Collections.Generic;
    
    public partial class EmbxprocesoRepositorio : BaseRepositorio<EMBXPROCESO>, IEmbxprocesoRepositorio
    {
    	public EmbxprocesoRepositorio(IContext context) : base(context) { }
    }
}
