//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROCJUD.Response
{
    using System;
    using System.Collections.Generic;
    
    public partial class EtapasResponse
    {
        public int id { get; set; }
        public Nullable<int> id_proceso { get; set; }
        public string descripcion { get; set; }
        public Nullable<System.DateTime> auditmod { get; set; }
        public string usuario { get; set; }
        public string anotacion { get; set; }
    }
}
