//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROCJUD.Response
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoPlazoResponse
    {
        public int id_plazo { get; set; }
        public int id_tipo_instancia { get; set; }
        public string nombre_plazo { get; set; }
        public Nullable<decimal> dias_plazo { get; set; }
    
        public virtual List<DatProcesoPlazoResponse> proceso_plazo { get; set; }
        public virtual TipoInstanciaResponse _instancia { get; set; }
    }
}
