//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROCJUD.Response
{
    using System;
    using System.Collections.Generic;
    
    public partial class VwDocumentoSitradocResponse
    {
        public int id_documento { get; set; }
        public Nullable<int> id_persona { get; set; }
        public Nullable<int> id_tup { get; set; }
        public int id_tipo_documento { get; set; }
        public int id_estado_documento { get; set; }
        public Nullable<int> id_clase_documento_interno { get; set; }
        public string num_tram_documentario { get; set; }
        public string indicativo_oficio { get; set; }
        public string asunto { get; set; }
        public Nullable<int> folios { get; set; }
        public string observaciones { get; set; }
        public string fecha_recepcion { get; set; }
        public string prioridad { get; set; }
        public string usuario { get; set; }
        public System.DateTime auditmod { get; set; }
        public string estado_requisito { get; set; }
        public string fecha2 { get; set; }
        public Nullable<int> coddep { get; set; }
        public string obsfin { get; set; }
        public string fecha3 { get; set; }
        public string modificacion { get; set; }
        public string referencia { get; set; }
        public string fecha_max_plazo { get; set; }
        public Nullable<int> v_asesor { get; set; }
        public Nullable<int> requerimiento { get; set; }
        public Nullable<int> coddep_responsable { get; set; }
        public Nullable<int> estado_expediente { get; set; }
        public Nullable<int> sujeto_proceso_judicial { get; set; }
        public string reporte_ocurrencia { get; set; }
    }
}
