//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROCJUD.Response
{
    using System;
    using System.Collections.Generic;
    
    public partial class VwPersonaResponse
    {
        public int id { get; set; }
        public int id_tipo_persona { get; set; }
        public string nombre { get; set; }
        public string nro_documento { get; set; }
        public string nro_docpernatural { get; set; }
    }
}
