//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROCJUD.Response
{
    using System;
    using System.Collections.Generic;
    
    public partial class VwProcesoResponse
    {
        public int id { get; set; }
        public string numero { get; set; }
        public string materia_descripcion { get; set; }
        public string naturaleza_descripcion { get; set; }
        public string tipo_proceso_descripcion { get; set; }
        public string abogado { get; set; }
        public string estado_descripcion { get; set; }
        public Nullable<int> estado_proceso { get; set; }
        public Nullable<int> id_abogado { get; set; }
        public Nullable<System.DateTime> auditmod { get; set; }
        public Nullable<int> id_materia { get; set; }
        public Nullable<int> id_naturaleza { get; set; }
        public Nullable<int> id_tipo_proceso { get; set; }
    }
}
