//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROCJUD.Response
{
    using System;
    using System.Collections.Generic;
    
    public partial class VwTipoProcesoResponse
    {
        public int id_tipo_proceso { get; set; }
        public Nullable<int> id_materia { get; set; }
        public string materia_descripcion { get; set; }
        public string tipo_proceso_descripcion { get; set; }
        public Nullable<int> estado_tipo_proceso { get; set; }
        public Nullable<int> orden_tipo_proceso { get; set; }
    }
}
