//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROCJUD.Web.ServiceReniec {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EnviarDatosdPersona", Namespace="http://schemas.datacontract.org/2004/07/WCFSistemasService")]
    [System.SerializableAttribute()]
    public partial class EnviarDatosdPersona : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ID_AMBIENTEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ID_DNIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ID_DNIUSEREMPField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID_AMBIENTE {
            get {
                return this.ID_AMBIENTEField;
            }
            set {
                if ((object.ReferenceEquals(this.ID_AMBIENTEField, value) != true)) {
                    this.ID_AMBIENTEField = value;
                    this.RaisePropertyChanged("ID_AMBIENTE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID_DNI {
            get {
                return this.ID_DNIField;
            }
            set {
                if ((object.ReferenceEquals(this.ID_DNIField, value) != true)) {
                    this.ID_DNIField = value;
                    this.RaisePropertyChanged("ID_DNI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID_DNIUSEREMP {
            get {
                return this.ID_DNIUSEREMPField;
            }
            set {
                if ((object.ReferenceEquals(this.ID_DNIUSEREMPField, value) != true)) {
                    this.ID_DNIUSEREMPField = value;
                    this.RaisePropertyChanged("ID_DNIUSEREMP");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BuscarPersonaResult", Namespace="http://schemas.datacontract.org/2004/07/WCFSistemasService")]
    [System.SerializableAttribute()]
    public partial class BuscarPersonaResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DES_DATO_01Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DES_DATO_02Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DES_DATO_03Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DES_DATO_04Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DES_DATO_05Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DES_DATO_06Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DES_DATO_07Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DES_DATO_08Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DES_DATO_09Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DES_DATO_10Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DES_DATO_11Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DES_DATO_12Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DES_DATO_13Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DES_DATO_14Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DES_DATO_15Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DES_DATO_16Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DES_DATO_17Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DES_DATO_18Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DES_DATO_19Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DES_DATO_20Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DES_DATO_21Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DES_DATO_22Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long ID_DNIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MiIPField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DES_DATO_01 {
            get {
                return this.DES_DATO_01Field;
            }
            set {
                if ((object.ReferenceEquals(this.DES_DATO_01Field, value) != true)) {
                    this.DES_DATO_01Field = value;
                    this.RaisePropertyChanged("DES_DATO_01");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DES_DATO_02 {
            get {
                return this.DES_DATO_02Field;
            }
            set {
                if ((object.ReferenceEquals(this.DES_DATO_02Field, value) != true)) {
                    this.DES_DATO_02Field = value;
                    this.RaisePropertyChanged("DES_DATO_02");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DES_DATO_03 {
            get {
                return this.DES_DATO_03Field;
            }
            set {
                if ((object.ReferenceEquals(this.DES_DATO_03Field, value) != true)) {
                    this.DES_DATO_03Field = value;
                    this.RaisePropertyChanged("DES_DATO_03");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DES_DATO_04 {
            get {
                return this.DES_DATO_04Field;
            }
            set {
                if ((object.ReferenceEquals(this.DES_DATO_04Field, value) != true)) {
                    this.DES_DATO_04Field = value;
                    this.RaisePropertyChanged("DES_DATO_04");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DES_DATO_05 {
            get {
                return this.DES_DATO_05Field;
            }
            set {
                if ((object.ReferenceEquals(this.DES_DATO_05Field, value) != true)) {
                    this.DES_DATO_05Field = value;
                    this.RaisePropertyChanged("DES_DATO_05");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DES_DATO_06 {
            get {
                return this.DES_DATO_06Field;
            }
            set {
                if ((object.ReferenceEquals(this.DES_DATO_06Field, value) != true)) {
                    this.DES_DATO_06Field = value;
                    this.RaisePropertyChanged("DES_DATO_06");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DES_DATO_07 {
            get {
                return this.DES_DATO_07Field;
            }
            set {
                if ((object.ReferenceEquals(this.DES_DATO_07Field, value) != true)) {
                    this.DES_DATO_07Field = value;
                    this.RaisePropertyChanged("DES_DATO_07");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DES_DATO_08 {
            get {
                return this.DES_DATO_08Field;
            }
            set {
                if ((object.ReferenceEquals(this.DES_DATO_08Field, value) != true)) {
                    this.DES_DATO_08Field = value;
                    this.RaisePropertyChanged("DES_DATO_08");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DES_DATO_09 {
            get {
                return this.DES_DATO_09Field;
            }
            set {
                if ((object.ReferenceEquals(this.DES_DATO_09Field, value) != true)) {
                    this.DES_DATO_09Field = value;
                    this.RaisePropertyChanged("DES_DATO_09");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DES_DATO_10 {
            get {
                return this.DES_DATO_10Field;
            }
            set {
                if ((object.ReferenceEquals(this.DES_DATO_10Field, value) != true)) {
                    this.DES_DATO_10Field = value;
                    this.RaisePropertyChanged("DES_DATO_10");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DES_DATO_11 {
            get {
                return this.DES_DATO_11Field;
            }
            set {
                if ((object.ReferenceEquals(this.DES_DATO_11Field, value) != true)) {
                    this.DES_DATO_11Field = value;
                    this.RaisePropertyChanged("DES_DATO_11");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DES_DATO_12 {
            get {
                return this.DES_DATO_12Field;
            }
            set {
                if ((object.ReferenceEquals(this.DES_DATO_12Field, value) != true)) {
                    this.DES_DATO_12Field = value;
                    this.RaisePropertyChanged("DES_DATO_12");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DES_DATO_13 {
            get {
                return this.DES_DATO_13Field;
            }
            set {
                if ((object.ReferenceEquals(this.DES_DATO_13Field, value) != true)) {
                    this.DES_DATO_13Field = value;
                    this.RaisePropertyChanged("DES_DATO_13");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DES_DATO_14 {
            get {
                return this.DES_DATO_14Field;
            }
            set {
                if ((object.ReferenceEquals(this.DES_DATO_14Field, value) != true)) {
                    this.DES_DATO_14Field = value;
                    this.RaisePropertyChanged("DES_DATO_14");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DES_DATO_15 {
            get {
                return this.DES_DATO_15Field;
            }
            set {
                if ((object.ReferenceEquals(this.DES_DATO_15Field, value) != true)) {
                    this.DES_DATO_15Field = value;
                    this.RaisePropertyChanged("DES_DATO_15");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DES_DATO_16 {
            get {
                return this.DES_DATO_16Field;
            }
            set {
                if ((object.ReferenceEquals(this.DES_DATO_16Field, value) != true)) {
                    this.DES_DATO_16Field = value;
                    this.RaisePropertyChanged("DES_DATO_16");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DES_DATO_17 {
            get {
                return this.DES_DATO_17Field;
            }
            set {
                if ((object.ReferenceEquals(this.DES_DATO_17Field, value) != true)) {
                    this.DES_DATO_17Field = value;
                    this.RaisePropertyChanged("DES_DATO_17");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DES_DATO_18 {
            get {
                return this.DES_DATO_18Field;
            }
            set {
                if ((object.ReferenceEquals(this.DES_DATO_18Field, value) != true)) {
                    this.DES_DATO_18Field = value;
                    this.RaisePropertyChanged("DES_DATO_18");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DES_DATO_19 {
            get {
                return this.DES_DATO_19Field;
            }
            set {
                if ((object.ReferenceEquals(this.DES_DATO_19Field, value) != true)) {
                    this.DES_DATO_19Field = value;
                    this.RaisePropertyChanged("DES_DATO_19");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DES_DATO_20 {
            get {
                return this.DES_DATO_20Field;
            }
            set {
                if ((object.ReferenceEquals(this.DES_DATO_20Field, value) != true)) {
                    this.DES_DATO_20Field = value;
                    this.RaisePropertyChanged("DES_DATO_20");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DES_DATO_21 {
            get {
                return this.DES_DATO_21Field;
            }
            set {
                if ((object.ReferenceEquals(this.DES_DATO_21Field, value) != true)) {
                    this.DES_DATO_21Field = value;
                    this.RaisePropertyChanged("DES_DATO_21");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DES_DATO_22 {
            get {
                return this.DES_DATO_22Field;
            }
            set {
                if ((object.ReferenceEquals(this.DES_DATO_22Field, value) != true)) {
                    this.DES_DATO_22Field = value;
                    this.RaisePropertyChanged("DES_DATO_22");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ID_DNI {
            get {
                return this.ID_DNIField;
            }
            set {
                if ((this.ID_DNIField.Equals(value) != true)) {
                    this.ID_DNIField = value;
                    this.RaisePropertyChanged("ID_DNI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MiIP {
            get {
                return this.MiIPField;
            }
            set {
                if ((object.ReferenceEquals(this.MiIPField, value) != true)) {
                    this.MiIPField = value;
                    this.RaisePropertyChanged("MiIP");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PersonaNaturalResponse", Namespace="http://schemas.datacontract.org/2004/07/WCFSistemasService")]
    [System.SerializableAttribute()]
    public partial class PersonaNaturalResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string APELLIDOSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime AUDIT_MODField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CELULARField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CODIGO_DEPARTAMENTOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CODIGO_DISTRITOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CODIGO_PROVINCIAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CODIGO_PUERTOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DIRECCIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EMAILField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FAXField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FLAGField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FLAG_OECField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ID_AURAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ID_SECTORField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ID_TIPO_IDENTIFICACIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ID_TIPO_IDENTIFICACION_REP_LEGField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ID_TIPO_ORGANIZACIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ID_TIPO_PERSONAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NOMBRESField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NRO_DOCPERNATURALField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NRO_DOCUMENTOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NRO_DOCUMENTO_REPRESENTANTEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OBSERVACIONESField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RAZON_SOCIALField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string REPRESENTANTE_LEGALField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RUBROField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TELEFONOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string mensajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string usuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string APELLIDOS {
            get {
                return this.APELLIDOSField;
            }
            set {
                if ((object.ReferenceEquals(this.APELLIDOSField, value) != true)) {
                    this.APELLIDOSField = value;
                    this.RaisePropertyChanged("APELLIDOS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime AUDIT_MOD {
            get {
                return this.AUDIT_MODField;
            }
            set {
                if ((this.AUDIT_MODField.Equals(value) != true)) {
                    this.AUDIT_MODField = value;
                    this.RaisePropertyChanged("AUDIT_MOD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CELULAR {
            get {
                return this.CELULARField;
            }
            set {
                if ((object.ReferenceEquals(this.CELULARField, value) != true)) {
                    this.CELULARField = value;
                    this.RaisePropertyChanged("CELULAR");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CODIGO_DEPARTAMENTO {
            get {
                return this.CODIGO_DEPARTAMENTOField;
            }
            set {
                if ((object.ReferenceEquals(this.CODIGO_DEPARTAMENTOField, value) != true)) {
                    this.CODIGO_DEPARTAMENTOField = value;
                    this.RaisePropertyChanged("CODIGO_DEPARTAMENTO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CODIGO_DISTRITO {
            get {
                return this.CODIGO_DISTRITOField;
            }
            set {
                if ((object.ReferenceEquals(this.CODIGO_DISTRITOField, value) != true)) {
                    this.CODIGO_DISTRITOField = value;
                    this.RaisePropertyChanged("CODIGO_DISTRITO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CODIGO_PROVINCIA {
            get {
                return this.CODIGO_PROVINCIAField;
            }
            set {
                if ((object.ReferenceEquals(this.CODIGO_PROVINCIAField, value) != true)) {
                    this.CODIGO_PROVINCIAField = value;
                    this.RaisePropertyChanged("CODIGO_PROVINCIA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CODIGO_PUERTO {
            get {
                return this.CODIGO_PUERTOField;
            }
            set {
                if ((this.CODIGO_PUERTOField.Equals(value) != true)) {
                    this.CODIGO_PUERTOField = value;
                    this.RaisePropertyChanged("CODIGO_PUERTO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DIRECCION {
            get {
                return this.DIRECCIONField;
            }
            set {
                if ((object.ReferenceEquals(this.DIRECCIONField, value) != true)) {
                    this.DIRECCIONField = value;
                    this.RaisePropertyChanged("DIRECCION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EMAIL {
            get {
                return this.EMAILField;
            }
            set {
                if ((object.ReferenceEquals(this.EMAILField, value) != true)) {
                    this.EMAILField = value;
                    this.RaisePropertyChanged("EMAIL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FAX {
            get {
                return this.FAXField;
            }
            set {
                if ((object.ReferenceEquals(this.FAXField, value) != true)) {
                    this.FAXField = value;
                    this.RaisePropertyChanged("FAX");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FLAG {
            get {
                return this.FLAGField;
            }
            set {
                if ((object.ReferenceEquals(this.FLAGField, value) != true)) {
                    this.FLAGField = value;
                    this.RaisePropertyChanged("FLAG");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FLAG_OEC {
            get {
                return this.FLAG_OECField;
            }
            set {
                if ((object.ReferenceEquals(this.FLAG_OECField, value) != true)) {
                    this.FLAG_OECField = value;
                    this.RaisePropertyChanged("FLAG_OEC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ID_AURA {
            get {
                return this.ID_AURAField;
            }
            set {
                if ((this.ID_AURAField.Equals(value) != true)) {
                    this.ID_AURAField = value;
                    this.RaisePropertyChanged("ID_AURA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_SECTOR {
            get {
                return this.ID_SECTORField;
            }
            set {
                if ((this.ID_SECTORField.Equals(value) != true)) {
                    this.ID_SECTORField = value;
                    this.RaisePropertyChanged("ID_SECTOR");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_TIPO_IDENTIFICACION {
            get {
                return this.ID_TIPO_IDENTIFICACIONField;
            }
            set {
                if ((this.ID_TIPO_IDENTIFICACIONField.Equals(value) != true)) {
                    this.ID_TIPO_IDENTIFICACIONField = value;
                    this.RaisePropertyChanged("ID_TIPO_IDENTIFICACION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ID_TIPO_IDENTIFICACION_REP_LEG {
            get {
                return this.ID_TIPO_IDENTIFICACION_REP_LEGField;
            }
            set {
                if ((this.ID_TIPO_IDENTIFICACION_REP_LEGField.Equals(value) != true)) {
                    this.ID_TIPO_IDENTIFICACION_REP_LEGField = value;
                    this.RaisePropertyChanged("ID_TIPO_IDENTIFICACION_REP_LEG");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ID_TIPO_ORGANIZACION {
            get {
                return this.ID_TIPO_ORGANIZACIONField;
            }
            set {
                if ((this.ID_TIPO_ORGANIZACIONField.Equals(value) != true)) {
                    this.ID_TIPO_ORGANIZACIONField = value;
                    this.RaisePropertyChanged("ID_TIPO_ORGANIZACION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_TIPO_PERSONA {
            get {
                return this.ID_TIPO_PERSONAField;
            }
            set {
                if ((this.ID_TIPO_PERSONAField.Equals(value) != true)) {
                    this.ID_TIPO_PERSONAField = value;
                    this.RaisePropertyChanged("ID_TIPO_PERSONA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NOMBRES {
            get {
                return this.NOMBRESField;
            }
            set {
                if ((object.ReferenceEquals(this.NOMBRESField, value) != true)) {
                    this.NOMBRESField = value;
                    this.RaisePropertyChanged("NOMBRES");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NRO_DOCPERNATURAL {
            get {
                return this.NRO_DOCPERNATURALField;
            }
            set {
                if ((object.ReferenceEquals(this.NRO_DOCPERNATURALField, value) != true)) {
                    this.NRO_DOCPERNATURALField = value;
                    this.RaisePropertyChanged("NRO_DOCPERNATURAL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NRO_DOCUMENTO {
            get {
                return this.NRO_DOCUMENTOField;
            }
            set {
                if ((object.ReferenceEquals(this.NRO_DOCUMENTOField, value) != true)) {
                    this.NRO_DOCUMENTOField = value;
                    this.RaisePropertyChanged("NRO_DOCUMENTO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NRO_DOCUMENTO_REPRESENTANTE {
            get {
                return this.NRO_DOCUMENTO_REPRESENTANTEField;
            }
            set {
                if ((object.ReferenceEquals(this.NRO_DOCUMENTO_REPRESENTANTEField, value) != true)) {
                    this.NRO_DOCUMENTO_REPRESENTANTEField = value;
                    this.RaisePropertyChanged("NRO_DOCUMENTO_REPRESENTANTE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OBSERVACIONES {
            get {
                return this.OBSERVACIONESField;
            }
            set {
                if ((object.ReferenceEquals(this.OBSERVACIONESField, value) != true)) {
                    this.OBSERVACIONESField = value;
                    this.RaisePropertyChanged("OBSERVACIONES");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RAZON_SOCIAL {
            get {
                return this.RAZON_SOCIALField;
            }
            set {
                if ((object.ReferenceEquals(this.RAZON_SOCIALField, value) != true)) {
                    this.RAZON_SOCIALField = value;
                    this.RaisePropertyChanged("RAZON_SOCIAL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string REPRESENTANTE_LEGAL {
            get {
                return this.REPRESENTANTE_LEGALField;
            }
            set {
                if ((object.ReferenceEquals(this.REPRESENTANTE_LEGALField, value) != true)) {
                    this.REPRESENTANTE_LEGALField = value;
                    this.RaisePropertyChanged("REPRESENTANTE_LEGAL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RUBRO {
            get {
                return this.RUBROField;
            }
            set {
                if ((object.ReferenceEquals(this.RUBROField, value) != true)) {
                    this.RUBROField = value;
                    this.RaisePropertyChanged("RUBRO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TELEFONO {
            get {
                return this.TELEFONOField;
            }
            set {
                if ((object.ReferenceEquals(this.TELEFONOField, value) != true)) {
                    this.TELEFONOField = value;
                    this.RaisePropertyChanged("TELEFONO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.mensajeField, value) != true)) {
                    this.mensajeField = value;
                    this.RaisePropertyChanged("mensaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string usuario {
            get {
                return this.usuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.usuarioField, value) != true)) {
                    this.usuarioField = value;
                    this.RaisePropertyChanged("usuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CarnetExtranjeriaRequest", Namespace="http://schemas.datacontract.org/2004/07/WCFSistemasService")]
    [System.SerializableAttribute()]
    public partial class CarnetExtranjeriaRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string APELLIDOSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CODIGO_DEPARTAMENTOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CODIGO_DISTRITOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CODIGO_PROVINCIAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DIRECCIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EMAILField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NOMBRESField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NRO_DOCUMENTOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TELEFONOField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string APELLIDOS {
            get {
                return this.APELLIDOSField;
            }
            set {
                if ((object.ReferenceEquals(this.APELLIDOSField, value) != true)) {
                    this.APELLIDOSField = value;
                    this.RaisePropertyChanged("APELLIDOS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CODIGO_DEPARTAMENTO {
            get {
                return this.CODIGO_DEPARTAMENTOField;
            }
            set {
                if ((object.ReferenceEquals(this.CODIGO_DEPARTAMENTOField, value) != true)) {
                    this.CODIGO_DEPARTAMENTOField = value;
                    this.RaisePropertyChanged("CODIGO_DEPARTAMENTO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CODIGO_DISTRITO {
            get {
                return this.CODIGO_DISTRITOField;
            }
            set {
                if ((object.ReferenceEquals(this.CODIGO_DISTRITOField, value) != true)) {
                    this.CODIGO_DISTRITOField = value;
                    this.RaisePropertyChanged("CODIGO_DISTRITO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CODIGO_PROVINCIA {
            get {
                return this.CODIGO_PROVINCIAField;
            }
            set {
                if ((object.ReferenceEquals(this.CODIGO_PROVINCIAField, value) != true)) {
                    this.CODIGO_PROVINCIAField = value;
                    this.RaisePropertyChanged("CODIGO_PROVINCIA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DIRECCION {
            get {
                return this.DIRECCIONField;
            }
            set {
                if ((object.ReferenceEquals(this.DIRECCIONField, value) != true)) {
                    this.DIRECCIONField = value;
                    this.RaisePropertyChanged("DIRECCION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EMAIL {
            get {
                return this.EMAILField;
            }
            set {
                if ((object.ReferenceEquals(this.EMAILField, value) != true)) {
                    this.EMAILField = value;
                    this.RaisePropertyChanged("EMAIL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NOMBRES {
            get {
                return this.NOMBRESField;
            }
            set {
                if ((object.ReferenceEquals(this.NOMBRESField, value) != true)) {
                    this.NOMBRESField = value;
                    this.RaisePropertyChanged("NOMBRES");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NRO_DOCUMENTO {
            get {
                return this.NRO_DOCUMENTOField;
            }
            set {
                if ((object.ReferenceEquals(this.NRO_DOCUMENTOField, value) != true)) {
                    this.NRO_DOCUMENTOField = value;
                    this.RaisePropertyChanged("NRO_DOCUMENTO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TELEFONO {
            get {
                return this.TELEFONOField;
            }
            set {
                if ((object.ReferenceEquals(this.TELEFONOField, value) != true)) {
                    this.TELEFONOField = value;
                    this.RaisePropertyChanged("TELEFONO");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReniec.IWCFSistemasService")]
    public interface IWCFSistemasService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFSistemasService/BuscarPersonaEnReniec", ReplyAction="http://tempuri.org/IWCFSistemasService/BuscarPersonaEnReniecResponse")]
        PROCJUD.Web.ServiceReniec.BuscarPersonaResult BuscarPersonaEnReniec(PROCJUD.Web.ServiceReniec.EnviarDatosdPersona Persona);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFSistemasService/BuscarPersonaEnReniec", ReplyAction="http://tempuri.org/IWCFSistemasService/BuscarPersonaEnReniecResponse")]
        System.Threading.Tasks.Task<PROCJUD.Web.ServiceReniec.BuscarPersonaResult> BuscarPersonaEnReniecAsync(PROCJUD.Web.ServiceReniec.EnviarDatosdPersona Persona);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFSistemasService/BuscarPersonaEnReniecParametro", ReplyAction="http://tempuri.org/IWCFSistemasService/BuscarPersonaEnReniecParametroResponse")]
        PROCJUD.Web.ServiceReniec.BuscarPersonaResult BuscarPersonaEnReniecParametro(string ID_DNI);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFSistemasService/BuscarPersonaEnReniecParametro", ReplyAction="http://tempuri.org/IWCFSistemasService/BuscarPersonaEnReniecParametroResponse")]
        System.Threading.Tasks.Task<PROCJUD.Web.ServiceReniec.BuscarPersonaResult> BuscarPersonaEnReniecParametroAsync(string ID_DNI);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFSistemasService/Validacion_RENIEC", ReplyAction="http://tempuri.org/IWCFSistemasService/Validacion_RENIECResponse")]
        PROCJUD.Web.ServiceReniec.BuscarPersonaResult Validacion_RENIEC(string ID_DNI);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFSistemasService/Validacion_RENIEC", ReplyAction="http://tempuri.org/IWCFSistemasService/Validacion_RENIECResponse")]
        System.Threading.Tasks.Task<PROCJUD.Web.ServiceReniec.BuscarPersonaResult> Validacion_RENIECAsync(string ID_DNI);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFSistemasService/Validacion_OGACI", ReplyAction="http://tempuri.org/IWCFSistemasService/Validacion_OGACIResponse")]
        PROCJUD.Web.ServiceReniec.BuscarPersonaResult Validacion_OGACI(string ID_DNI);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFSistemasService/Validacion_OGACI", ReplyAction="http://tempuri.org/IWCFSistemasService/Validacion_OGACIResponse")]
        System.Threading.Tasks.Task<PROCJUD.Web.ServiceReniec.BuscarPersonaResult> Validacion_OGACIAsync(string ID_DNI);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFSistemasService/BuscarReniecProduccion", ReplyAction="http://tempuri.org/IWCFSistemasService/BuscarReniecProduccionResponse")]
        PROCJUD.Web.ServiceReniec.BuscarPersonaResult BuscarReniecProduccion(PROCJUD.Web.ServiceReniec.EnviarDatosdPersona Persona);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFSistemasService/BuscarReniecProduccion", ReplyAction="http://tempuri.org/IWCFSistemasService/BuscarReniecProduccionResponse")]
        System.Threading.Tasks.Task<PROCJUD.Web.ServiceReniec.BuscarPersonaResult> BuscarReniecProduccionAsync(PROCJUD.Web.ServiceReniec.EnviarDatosdPersona Persona);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFSistemasService/BuscarReniecProduccionActualizadoParametro" +
            "", ReplyAction="http://tempuri.org/IWCFSistemasService/BuscarReniecProduccionActualizadoParametro" +
            "Response")]
        PROCJUD.Web.ServiceReniec.BuscarPersonaResult BuscarReniecProduccionActualizadoParametro(string ID_DNI);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFSistemasService/BuscarReniecProduccionActualizadoParametro" +
            "", ReplyAction="http://tempuri.org/IWCFSistemasService/BuscarReniecProduccionActualizadoParametro" +
            "Response")]
        System.Threading.Tasks.Task<PROCJUD.Web.ServiceReniec.BuscarPersonaResult> BuscarReniecProduccionActualizadoParametroAsync(string ID_DNI);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFSistemasService/BuscarReniecProduccionParametro", ReplyAction="http://tempuri.org/IWCFSistemasService/BuscarReniecProduccionParametroResponse")]
        PROCJUD.Web.ServiceReniec.BuscarPersonaResult BuscarReniecProduccionParametro(string ID_DNIUSEREMP, string ID_DNI);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFSistemasService/BuscarReniecProduccionParametro", ReplyAction="http://tempuri.org/IWCFSistemasService/BuscarReniecProduccionParametroResponse")]
        System.Threading.Tasks.Task<PROCJUD.Web.ServiceReniec.BuscarPersonaResult> BuscarReniecProduccionParametroAsync(string ID_DNIUSEREMP, string ID_DNI);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFSistemasService/Persona_Natural_Reniec", ReplyAction="http://tempuri.org/IWCFSistemasService/Persona_Natural_ReniecResponse")]
        PROCJUD.Web.ServiceReniec.PersonaNaturalResponse Persona_Natural_Reniec(string DNI);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFSistemasService/Persona_Natural_Reniec", ReplyAction="http://tempuri.org/IWCFSistemasService/Persona_Natural_ReniecResponse")]
        System.Threading.Tasks.Task<PROCJUD.Web.ServiceReniec.PersonaNaturalResponse> Persona_Natural_ReniecAsync(string DNI);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFSistemasService/GuardarCarnetExtranjeria", ReplyAction="http://tempuri.org/IWCFSistemasService/GuardarCarnetExtranjeriaResponse")]
        PROCJUD.Web.ServiceReniec.PersonaNaturalResponse GuardarCarnetExtranjeria(PROCJUD.Web.ServiceReniec.CarnetExtranjeriaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFSistemasService/GuardarCarnetExtranjeria", ReplyAction="http://tempuri.org/IWCFSistemasService/GuardarCarnetExtranjeriaResponse")]
        System.Threading.Tasks.Task<PROCJUD.Web.ServiceReniec.PersonaNaturalResponse> GuardarCarnetExtranjeriaAsync(PROCJUD.Web.ServiceReniec.CarnetExtranjeriaRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWCFSistemasServiceChannel : PROCJUD.Web.ServiceReniec.IWCFSistemasService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WCFSistemasServiceClient : System.ServiceModel.ClientBase<PROCJUD.Web.ServiceReniec.IWCFSistemasService>, PROCJUD.Web.ServiceReniec.IWCFSistemasService {
        
        public WCFSistemasServiceClient() {
        }
        
        public WCFSistemasServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WCFSistemasServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WCFSistemasServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WCFSistemasServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public PROCJUD.Web.ServiceReniec.BuscarPersonaResult BuscarPersonaEnReniec(PROCJUD.Web.ServiceReniec.EnviarDatosdPersona Persona) {
            return base.Channel.BuscarPersonaEnReniec(Persona);
        }
        
        public System.Threading.Tasks.Task<PROCJUD.Web.ServiceReniec.BuscarPersonaResult> BuscarPersonaEnReniecAsync(PROCJUD.Web.ServiceReniec.EnviarDatosdPersona Persona) {
            return base.Channel.BuscarPersonaEnReniecAsync(Persona);
        }
        
        public PROCJUD.Web.ServiceReniec.BuscarPersonaResult BuscarPersonaEnReniecParametro(string ID_DNI) {
            return base.Channel.BuscarPersonaEnReniecParametro(ID_DNI);
        }
        
        public System.Threading.Tasks.Task<PROCJUD.Web.ServiceReniec.BuscarPersonaResult> BuscarPersonaEnReniecParametroAsync(string ID_DNI) {
            return base.Channel.BuscarPersonaEnReniecParametroAsync(ID_DNI);
        }
        
        public PROCJUD.Web.ServiceReniec.BuscarPersonaResult Validacion_RENIEC(string ID_DNI) {
            return base.Channel.Validacion_RENIEC(ID_DNI);
        }
        
        public System.Threading.Tasks.Task<PROCJUD.Web.ServiceReniec.BuscarPersonaResult> Validacion_RENIECAsync(string ID_DNI) {
            return base.Channel.Validacion_RENIECAsync(ID_DNI);
        }
        
        public PROCJUD.Web.ServiceReniec.BuscarPersonaResult Validacion_OGACI(string ID_DNI) {
            return base.Channel.Validacion_OGACI(ID_DNI);
        }
        
        public System.Threading.Tasks.Task<PROCJUD.Web.ServiceReniec.BuscarPersonaResult> Validacion_OGACIAsync(string ID_DNI) {
            return base.Channel.Validacion_OGACIAsync(ID_DNI);
        }
        
        public PROCJUD.Web.ServiceReniec.BuscarPersonaResult BuscarReniecProduccion(PROCJUD.Web.ServiceReniec.EnviarDatosdPersona Persona) {
            return base.Channel.BuscarReniecProduccion(Persona);
        }
        
        public System.Threading.Tasks.Task<PROCJUD.Web.ServiceReniec.BuscarPersonaResult> BuscarReniecProduccionAsync(PROCJUD.Web.ServiceReniec.EnviarDatosdPersona Persona) {
            return base.Channel.BuscarReniecProduccionAsync(Persona);
        }
        
        public PROCJUD.Web.ServiceReniec.BuscarPersonaResult BuscarReniecProduccionActualizadoParametro(string ID_DNI) {
            return base.Channel.BuscarReniecProduccionActualizadoParametro(ID_DNI);
        }
        
        public System.Threading.Tasks.Task<PROCJUD.Web.ServiceReniec.BuscarPersonaResult> BuscarReniecProduccionActualizadoParametroAsync(string ID_DNI) {
            return base.Channel.BuscarReniecProduccionActualizadoParametroAsync(ID_DNI);
        }
        
        public PROCJUD.Web.ServiceReniec.BuscarPersonaResult BuscarReniecProduccionParametro(string ID_DNIUSEREMP, string ID_DNI) {
            return base.Channel.BuscarReniecProduccionParametro(ID_DNIUSEREMP, ID_DNI);
        }
        
        public System.Threading.Tasks.Task<PROCJUD.Web.ServiceReniec.BuscarPersonaResult> BuscarReniecProduccionParametroAsync(string ID_DNIUSEREMP, string ID_DNI) {
            return base.Channel.BuscarReniecProduccionParametroAsync(ID_DNIUSEREMP, ID_DNI);
        }
        
        public PROCJUD.Web.ServiceReniec.PersonaNaturalResponse Persona_Natural_Reniec(string DNI) {
            return base.Channel.Persona_Natural_Reniec(DNI);
        }
        
        public System.Threading.Tasks.Task<PROCJUD.Web.ServiceReniec.PersonaNaturalResponse> Persona_Natural_ReniecAsync(string DNI) {
            return base.Channel.Persona_Natural_ReniecAsync(DNI);
        }
        
        public PROCJUD.Web.ServiceReniec.PersonaNaturalResponse GuardarCarnetExtranjeria(PROCJUD.Web.ServiceReniec.CarnetExtranjeriaRequest request) {
            return base.Channel.GuardarCarnetExtranjeria(request);
        }
        
        public System.Threading.Tasks.Task<PROCJUD.Web.ServiceReniec.PersonaNaturalResponse> GuardarCarnetExtranjeriaAsync(PROCJUD.Web.ServiceReniec.CarnetExtranjeriaRequest request) {
            return base.Channel.GuardarCarnetExtranjeriaAsync(request);
        }
    }
}
