//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROCJUD.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class dat_materia_tipo_proceso
    {
        public int id_materia { get; set; }
        public int id_tipo_proceso { get; set; }
        public Nullable<int> estado { get; set; }
    }
}
