//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROCJUD.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class DAT_PROCESO_INSTANCIA_DOCUMENTO
    {
        public int id_proceso_instancia_documento { get; set; }
        public Nullable<int> id_proceso_instancia { get; set; }
        public Nullable<int> id_documento { get; set; }
        public string numero_documento { get; set; }
        public Nullable<System.DateTime> fecha_documento { get; set; }
        public string archivo { get; set; }
    
        public virtual DAT_PROCESO_INSTANCIA DAT_PROCESO_INSTANCIA { get; set; }
    }
}
