//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROCJUD.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class opd
    {
        public int id_opd { get; set; }
        public Nullable<int> id_persona { get; set; }
        public string descripcion { get; set; }
        public Nullable<bool> estado { get; set; }
    }
}
