//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROCJUD.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROCESO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
         public PROCESO()
         {
             this.DAT_PROCESO_INSTANCIA = new HashSet<DAT_PROCESO_INSTANCIA>();  
         }
    
        public int id { get; set; }
        public Nullable<int> id_documento { get; set; }
        public Nullable<int> id_naturaleza { get; set; }
        public Nullable<decimal> monto { get; set; }
        public Nullable<int> id_tipo_proceso { get; set; }
        public Nullable<int> id_tipo_responsabilidad { get; set; }
        public string codigo_departamento { get; set; }
        public string codigo_provincia { get; set; }
        public string codigo_distrito { get; set; }
        public string flag { get; set; }
        public Nullable<System.DateTime> auditmod { get; set; }
        public string usuario { get; set; }
        public string avance { get; set; }
        public Nullable<int> materia { get; set; }
        public string delito { get; set; }
        public string juzgado { get; set; }
        public string exp1 { get; set; }
        public string sala { get; set; }
        public string exp2 { get; set; }
        public string corte { get; set; }
        public string exp3 { get; set; }
        public string correlativo { get; set; }
        public string codigo_distritojudicial { get; set; }
        public string codigo_sede { get; set; }
        public string fecVenc { get; set; }
        public string AUTORITATIVA { get; set; }
        public string JUZGADO2 { get; set; }
        public string EXP4 { get; set; }
        public string JUZGADO3 { get; set; }
        public string EXP5 { get; set; }
        public string JUZGADO4 { get; set; }
        public string EXP6 { get; set; }
        public string SALA2 { get; set; }
        public string EXP7 { get; set; }
        public string SALA3 { get; set; }
        public string EXP8 { get; set; }
        public string SALA4 { get; set; }
        public string EXP9 { get; set; }
        public string SALA5 { get; set; }
        public string EXP10 { get; set; }
        public Nullable<int> ID_RESOLUCION_AUTORITATIVA { get; set; }
        public Nullable<int> ID_ABOGADO { get; set; }
        public string JUZGADO_PAZ { get; set; }
        public string EXPEDIENTE_JUZGADO_PAZ { get; set; }
        public string ESPECIALISTA_JUZGADO_PAZ { get; set; }
        public string TRIBUNAL { get; set; }
        public string EXPEDIENTE_TRIBUNAL { get; set; }
        public string ESPECIALISTA_TRIBUNAL { get; set; }
        public string ESPECIALISTA_JUZGADO_FISCALIA { get; set; }
        public string ESPECIALISTA_SALA_SUPERIOR { get; set; }
        public string ESPECIALISTA_CORTE_SUPREMA { get; set; }
        public Nullable<int> ESTADO_PROCESO { get; set; }
        public Nullable<int> TIPO_FINALIZACION { get; set; }
        public string RESOLUCION_FINALIZACION { get; set; }
        public string FECHA_FINALIZACION { get; set; }
        public Nullable<int> ESTADO_ARCHIVAMIENTO { get; set; }
        public Nullable<decimal> MONTO_FINALIZACION { get; set; }
        public Nullable<System.DateTime> AUDIT_FINALIZACION { get; set; }
        public string USUARIO_FINALIZACION { get; set; }
        public string MOTIVO_FINALIZACION { get; set; }
        public string EMBCLONADA1 { get; set; }
        public string MATRICOLNADA1 { get; set; }
        public string EMBCLONADA2 { get; set; }
        public string MATRICLONADA2 { get; set; }
        public string EMBCLONADA3 { get; set; }
        public string MATRICLONADA3 { get; set; }
        public Nullable<int> ID_TIPO_MONTO { get; set; }
        public Nullable<int> ID_ETAPA_PROCESAL { get; set; }
        public Nullable<decimal> UIT { get; set; }
        public string sector { get; set; }
        public Nullable<int> id_opd { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DAT_PROCESO_INSTANCIA> DAT_PROCESO_INSTANCIA { get; set; }
        public virtual ICollection<PROCESO> PROCESOs { get; set; }
    }
}
