//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROCJUD.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPO_PLAZO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TIPO_PLAZO()
        {
            this.DAT_PROCESO_PLAZO = new HashSet<DAT_PROCESO_PLAZO>();
        }
    
        public int id_plazo { get; set; }
        public int id_tipo_instancia { get; set; }
        public string nombre_plazo { get; set; }
        public Nullable<decimal> dias_plazo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DAT_PROCESO_PLAZO> DAT_PROCESO_PLAZO { get; set; }
        public virtual TIPO_INSTANCIA TIPO_INSTANCIA { get; set; }
    }
}
