//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROCJUD.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPO_INSTANCIA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TIPO_INSTANCIA()
        {
            this.DAT_PROCESO_INSTANCIA = new HashSet<DAT_PROCESO_INSTANCIA>();
            this.TIPO_PLAZO = new HashSet<TIPO_PLAZO>();
        }
    
        public int id_tipo_instancia { get; set; }
        public Nullable<int> id_tipo_proceso { get; set; }
        public string nombre_tipo_instancia { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DAT_PROCESO_INSTANCIA> DAT_PROCESO_INSTANCIA { get; set; }
        public virtual tipo_proceso tipo_proceso { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TIPO_PLAZO> TIPO_PLAZO { get; set; }
    }
}
