//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROCJUD.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class tipo_proceso
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tipo_proceso()
        {
            this.TIPO_INSTANCIA = new HashSet<TIPO_INSTANCIA>();
        }
    
        public int id { get; set; }
        public Nullable<int> id_materia { get; set; }
        public string descripcion { get; set; }
        public Nullable<int> estado { get; set; }
        public Nullable<int> orden { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TIPO_INSTANCIA> TIPO_INSTANCIA { get; set; }
    }
}
