//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROCJUD.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_DOCUMENTO_SITRADOC
    {
        public int ID_DOCUMENTO { get; set; }
        public Nullable<int> ID_PERSONA { get; set; }
        public Nullable<int> ID_TUP { get; set; }
        public int ID_TIPO_DOCUMENTO { get; set; }
        public int ID_ESTADO_DOCUMENTO { get; set; }
        public Nullable<int> ID_CLASE_DOCUMENTO_INTERNO { get; set; }
        public string NUM_TRAM_DOCUMENTARIO { get; set; }
        public string INDICATIVO_OFICIO { get; set; }
        public string ASUNTO { get; set; }
        public Nullable<int> FOLIOS { get; set; }
        public string OBSERVACIONES { get; set; }
        public string FECHA_RECEPCION { get; set; }
        public string PRIORIDAD { get; set; }
        public string USUARIO { get; set; }
        public System.DateTime AUDITMOD { get; set; }
        public string ESTADO_REQUISITO { get; set; }
        public string FECHA2 { get; set; }
        public Nullable<int> coddep { get; set; }
        public string OBSFIN { get; set; }
        public string fecha3 { get; set; }
        public string modificacion { get; set; }
        public string referencia { get; set; }
        public string Fecha_Max_Plazo { get; set; }
        public Nullable<int> v_asesor { get; set; }
        public Nullable<int> requerimiento { get; set; }
        public Nullable<int> coddep_responsable { get; set; }
        public Nullable<int> ESTADO_EXPEDIENTE { get; set; }
        public Nullable<int> SUJETO_PROCESO_JUDICIAL { get; set; }
        public string REPORTE_OCURRENCIA { get; set; }
    }
}
