//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROCJUD.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_EMBARCACION
    {
        public int ID_EMB { get; set; }
        public string NOMBRE_EMB { get; set; }
        public string MATRICULA_EMB { get; set; }
    }
}
