//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROCJUD.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_TRABAJADOR_PRODUCE
    {
        public int CODIGO_TRABAJADOR { get; set; }
        public string NOMBRES_TRABAJADOR { get; set; }
        public string APELLIDOS_TRABAJADOR { get; set; }
        public Nullable<int> CODDEP { get; set; }
        public string ESTADO { get; set; }
        public string CONDICION { get; set; }
    }
}
