//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROCJUD.Request
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatProcesoInstanciaDocumentoRequest
    {
        public int id_proceso_instancia_documento { get; set; }
        public Nullable<int> id_proceso_instancia { get; set; }
        public Nullable<int> id_documento { get; set; }
        public string numero_documento { get; set; }
        public Nullable<System.DateTime> fecha_documento { get; set; }
        public string archivo { get; set; }
    
        public virtual DatProcesoInstanciaRequest proceso_instancia { get; set; }
    }
}
