//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROCJUD.Request
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExcepcionxprocesoRequest
    {
        public int id { get; set; }
        public int id_proceso { get; set; }
        public int id_tipo_excepcion { get; set; }
        public string excepcion { get; set; }
        public System.DateTime auditmod { get; set; }
        public string usuario { get; set; }
    }
}
