//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROCJUD.Request
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProcesoRequest
    {
        public int id { get; set; }
        public Nullable<int> id_documento { get; set; }
        public Nullable<int> id_naturaleza { get; set; }
        public Nullable<decimal> monto { get; set; }
        public Nullable<int> id_tipo_proceso { get; set; }
        public Nullable<int> id_tipo_responsabilidad { get; set; }
        public string codigo_departamento { get; set; }
        public string codigo_provincia { get; set; }
        public string codigo_distrito { get; set; }
        public string flag { get; set; }
        public Nullable<System.DateTime> auditmod { get; set; }
        public string usuario { get; set; }
        public string avance { get; set; }
        public Nullable<int> materia { get; set; }
        public string delito { get; set; }
        public string juzgado { get; set; }
        public string exp1 { get; set; }
        public string sala { get; set; }
        public string exp2 { get; set; }
        public string corte { get; set; }
        public string exp3 { get; set; }
        public string correlativo { get; set; }
        public string codigo_distritojudicial { get; set; }
        public string codigo_sede { get; set; }
        public string fecvenc { get; set; }
        public string autoritativa { get; set; }
        public string juzgado2 { get; set; }
        public string exp4 { get; set; }
        public string juzgado3 { get; set; }
        public string exp5 { get; set; }
        public string juzgado4 { get; set; }
        public string exp6 { get; set; }
        public string sala2 { get; set; }
        public string exp7 { get; set; }
        public string sala3 { get; set; }
        public string exp8 { get; set; }
        public string sala4 { get; set; }
        public string exp9 { get; set; }
        public string sala5 { get; set; }
        public string exp10 { get; set; }
        public Nullable<int> id_resolucion_autoritativa { get; set; }
        public Nullable<int> id_abogado { get; set; }
        public string juzgado_paz { get; set; }
        public string expediente_juzgado_paz { get; set; }
        public string especialista_juzgado_paz { get; set; }
        public string tribunal { get; set; }
        public string expediente_tribunal { get; set; }
        public string especialista_tribunal { get; set; }
        public string especialista_juzgado_fiscalia { get; set; }
        public string especialista_sala_superior { get; set; }
        public string especialista_corte_suprema { get; set; }
        public Nullable<int> estado_proceso { get; set; }
        public Nullable<int> tipo_finalizacion { get; set; }
        public string resolucion_finalizacion { get; set; }
        public string fecha_finalizacion { get; set; }
        public Nullable<int> estado_archivamiento { get; set; }
        public Nullable<decimal> monto_finalizacion { get; set; }
        public Nullable<System.DateTime> audit_finalizacion { get; set; }
        public string usuario_finalizacion { get; set; }
        public string motivo_finalizacion { get; set; }
        public string embclonada1 { get; set; }
        public string matricolnada1 { get; set; }
        public string embclonada2 { get; set; }
        public string matriclonada2 { get; set; }
        public string embclonada3 { get; set; }
        public string matriclonada3 { get; set; }
        public Nullable<int> id_tipo_monto { get; set; }
        public Nullable<int> id_etapa_procesal { get; set; }
        public Nullable<decimal> uit { get; set; }
        public string sector { get; set; }
        public Nullable<int> id_opd { get; set; }
    
        public virtual List<DatProcesoInstanciaRequest> proceso_instancia { get; set; }
    }
}
