//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROCJUD.Request
{
    using System;
    using System.Collections.Generic;
    
    public partial class VwDatProcesoPlazoRequest
    {
        public Nullable<int> id_materia { get; set; }
        public string materia_descripcion { get; set; }
        public Nullable<int> id_naturaleza { get; set; }
        public string naturaleza_descripcion { get; set; }
        public Nullable<int> id_tipo_proceso { get; set; }
        public string tipo_proceso_descripcion { get; set; }
        public string correlativo { get; set; }
        public Nullable<int> id_tipo_instancia { get; set; }
        public string nombre_tipo_instancia { get; set; }
        public int id_proceso_instancia { get; set; }
        public string nombre_instancia { get; set; }
        public string numero_instancia { get; set; }
        public Nullable<System.DateTime> fecha_inicio_instancia { get; set; }
        public Nullable<System.DateTime> fecha_final_instancia { get; set; }
        public int id_plazo { get; set; }
        public string nombre_plazo { get; set; }
        public Nullable<int> id_abogado { get; set; }
        public string nombre_apellido { get; set; }
        public Nullable<System.DateTime> fecha_inicio_plazo { get; set; }
        public Nullable<System.DateTime> fecha_final_plazo { get; set; }
        public string estado { get; set; }
        public string anotacion { get; set; }
        public Nullable<decimal> dias_plazo { get; set; }
        public Nullable<int> diferencia { get; set; }
        public Nullable<decimal> diferencia_dias { get; set; }
        public string color_alerta { get; set; }
    }
}
