//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROCJUD.Request
{
    using System;
    using System.Collections.Generic;
    
    public partial class VwEmbarcacionRequest
    {
        public int id_emb { get; set; }
        public string nombre_emb { get; set; }
        public string matricula_emb { get; set; }
    }
}
