//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROCJUD.Request
{
    using System;
    using System.Collections.Generic;
    
    public partial class VwResolucionSitradocRequest
    {
        public int id { get; set; }
        public string nro_resol { get; set; }
        public Nullable<int> id_documento { get; set; }
        public string flag { get; set; }
        public string sumilla { get; set; }
        public Nullable<int> id_tipo_resolucion { get; set; }
        public Nullable<System.DateTime> auditmod { get; set; }
        public string usuario { get; set; }
        public Nullable<System.DateTime> auditmod2 { get; set; }
        public string usuario2 { get; set; }
        public string fini { get; set; }
        public string ffin { get; set; }
        public string fpublicacion { get; set; }
        public Nullable<int> coddep { get; set; }
        public string ffirma { get; set; }
        public string ferratas { get; set; }
    }
}
