//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROCJUD.Request
{
    using System;
    using System.Collections.Generic;
    
    public partial class VwTrabajadorProduceRequest
    {
        public int codigo_trabajador { get; set; }
        public string nombres_trabajador { get; set; }
        public string apellidos_trabajador { get; set; }
        public Nullable<int> coddep { get; set; }
        public string estado { get; set; }
        public string condicion { get; set; }
    }
}
