//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROCJUD.Web.ServiceSunat {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BuscarEmpresaResult", Namespace="http://schemas.datacontract.org/2004/07/WCFSistemasService")]
    [System.SerializableAttribute()]
    public partial class BuscarEmpresaResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PROCJUD.Web.ServiceSunat.DatosEstablecimientoAnexo[] DatosEstablecimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PROCJUD.Web.ServiceSunat.DatosSecundariosdelContribuyente DatosSecundariosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ddp_ciiuFieldField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ddp_estadoFieldField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ddp_fecactFieldField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ddp_fecaltFieldField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ddp_fecbajFieldField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ddp_flag22FieldField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ddp_identiFieldField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ddp_inter1FieldField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ddp_llltttFieldField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ddp_nombreFieldField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ddp_nomviaFieldField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ddp_nomzonFieldField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ddp_numer1FieldField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ddp_numregFieldField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ddp_numrucFieldField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ddp_refer1FieldField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ddp_resultadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ddp_secuenFieldField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ddp_tipviaFieldField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ddp_tipzonFieldField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ddp_tpoempFieldField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ddp_ubigeoFieldField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string desc_tipviaFieldField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PROCJUD.Web.ServiceSunat.ListarRepLegales[] representanteslegalesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PROCJUD.Web.ServiceSunat.DatosEstablecimientoAnexo[] DatosEstablecimiento {
            get {
                return this.DatosEstablecimientoField;
            }
            set {
                if ((object.ReferenceEquals(this.DatosEstablecimientoField, value) != true)) {
                    this.DatosEstablecimientoField = value;
                    this.RaisePropertyChanged("DatosEstablecimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PROCJUD.Web.ServiceSunat.DatosSecundariosdelContribuyente DatosSecundarios {
            get {
                return this.DatosSecundariosField;
            }
            set {
                if ((object.ReferenceEquals(this.DatosSecundariosField, value) != true)) {
                    this.DatosSecundariosField = value;
                    this.RaisePropertyChanged("DatosSecundarios");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ddp_ciiuField {
            get {
                return this.ddp_ciiuFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.ddp_ciiuFieldField, value) != true)) {
                    this.ddp_ciiuFieldField = value;
                    this.RaisePropertyChanged("ddp_ciiuField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ddp_estadoField {
            get {
                return this.ddp_estadoFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.ddp_estadoFieldField, value) != true)) {
                    this.ddp_estadoFieldField = value;
                    this.RaisePropertyChanged("ddp_estadoField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ddp_fecactField {
            get {
                return this.ddp_fecactFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.ddp_fecactFieldField, value) != true)) {
                    this.ddp_fecactFieldField = value;
                    this.RaisePropertyChanged("ddp_fecactField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ddp_fecaltField {
            get {
                return this.ddp_fecaltFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.ddp_fecaltFieldField, value) != true)) {
                    this.ddp_fecaltFieldField = value;
                    this.RaisePropertyChanged("ddp_fecaltField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ddp_fecbajField {
            get {
                return this.ddp_fecbajFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.ddp_fecbajFieldField, value) != true)) {
                    this.ddp_fecbajFieldField = value;
                    this.RaisePropertyChanged("ddp_fecbajField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ddp_flag22Field {
            get {
                return this.ddp_flag22FieldField;
            }
            set {
                if ((object.ReferenceEquals(this.ddp_flag22FieldField, value) != true)) {
                    this.ddp_flag22FieldField = value;
                    this.RaisePropertyChanged("ddp_flag22Field");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ddp_identiField {
            get {
                return this.ddp_identiFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.ddp_identiFieldField, value) != true)) {
                    this.ddp_identiFieldField = value;
                    this.RaisePropertyChanged("ddp_identiField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ddp_inter1Field {
            get {
                return this.ddp_inter1FieldField;
            }
            set {
                if ((object.ReferenceEquals(this.ddp_inter1FieldField, value) != true)) {
                    this.ddp_inter1FieldField = value;
                    this.RaisePropertyChanged("ddp_inter1Field");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ddp_llltttField {
            get {
                return this.ddp_llltttFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.ddp_llltttFieldField, value) != true)) {
                    this.ddp_llltttFieldField = value;
                    this.RaisePropertyChanged("ddp_llltttField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ddp_nombreField {
            get {
                return this.ddp_nombreFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.ddp_nombreFieldField, value) != true)) {
                    this.ddp_nombreFieldField = value;
                    this.RaisePropertyChanged("ddp_nombreField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ddp_nomviaField {
            get {
                return this.ddp_nomviaFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.ddp_nomviaFieldField, value) != true)) {
                    this.ddp_nomviaFieldField = value;
                    this.RaisePropertyChanged("ddp_nomviaField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ddp_nomzonField {
            get {
                return this.ddp_nomzonFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.ddp_nomzonFieldField, value) != true)) {
                    this.ddp_nomzonFieldField = value;
                    this.RaisePropertyChanged("ddp_nomzonField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ddp_numer1Field {
            get {
                return this.ddp_numer1FieldField;
            }
            set {
                if ((object.ReferenceEquals(this.ddp_numer1FieldField, value) != true)) {
                    this.ddp_numer1FieldField = value;
                    this.RaisePropertyChanged("ddp_numer1Field");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ddp_numregField {
            get {
                return this.ddp_numregFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.ddp_numregFieldField, value) != true)) {
                    this.ddp_numregFieldField = value;
                    this.RaisePropertyChanged("ddp_numregField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ddp_numrucField {
            get {
                return this.ddp_numrucFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.ddp_numrucFieldField, value) != true)) {
                    this.ddp_numrucFieldField = value;
                    this.RaisePropertyChanged("ddp_numrucField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ddp_refer1Field {
            get {
                return this.ddp_refer1FieldField;
            }
            set {
                if ((object.ReferenceEquals(this.ddp_refer1FieldField, value) != true)) {
                    this.ddp_refer1FieldField = value;
                    this.RaisePropertyChanged("ddp_refer1Field");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ddp_resultado {
            get {
                return this.ddp_resultadoField;
            }
            set {
                if ((object.ReferenceEquals(this.ddp_resultadoField, value) != true)) {
                    this.ddp_resultadoField = value;
                    this.RaisePropertyChanged("ddp_resultado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ddp_secuenField {
            get {
                return this.ddp_secuenFieldField;
            }
            set {
                if ((this.ddp_secuenFieldField.Equals(value) != true)) {
                    this.ddp_secuenFieldField = value;
                    this.RaisePropertyChanged("ddp_secuenField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ddp_tipviaField {
            get {
                return this.ddp_tipviaFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.ddp_tipviaFieldField, value) != true)) {
                    this.ddp_tipviaFieldField = value;
                    this.RaisePropertyChanged("ddp_tipviaField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ddp_tipzonField {
            get {
                return this.ddp_tipzonFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.ddp_tipzonFieldField, value) != true)) {
                    this.ddp_tipzonFieldField = value;
                    this.RaisePropertyChanged("ddp_tipzonField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ddp_tpoempField {
            get {
                return this.ddp_tpoempFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.ddp_tpoempFieldField, value) != true)) {
                    this.ddp_tpoempFieldField = value;
                    this.RaisePropertyChanged("ddp_tpoempField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ddp_ubigeoField {
            get {
                return this.ddp_ubigeoFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.ddp_ubigeoFieldField, value) != true)) {
                    this.ddp_ubigeoFieldField = value;
                    this.RaisePropertyChanged("ddp_ubigeoField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string desc_tipviaField {
            get {
                return this.desc_tipviaFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.desc_tipviaFieldField, value) != true)) {
                    this.desc_tipviaFieldField = value;
                    this.RaisePropertyChanged("desc_tipviaField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PROCJUD.Web.ServiceSunat.ListarRepLegales[] representanteslegales {
            get {
                return this.representanteslegalesField;
            }
            set {
                if ((object.ReferenceEquals(this.representanteslegalesField, value) != true)) {
                    this.representanteslegalesField = value;
                    this.RaisePropertyChanged("representanteslegales");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DatosSecundariosdelContribuyente", Namespace="http://schemas.datacontract.org/2004/07/WCFSistemasService")]
    [System.SerializableAttribute()]
    public partial class DatosSecundariosdelContribuyente : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string dds_asientFieldField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string dds_comextFieldField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string dds_constiFieldField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string dds_contabFieldField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string dds_docideFieldField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string dds_domiciFieldField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string dds_facturFieldField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string dds_fecactFieldField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string dds_fecnacFieldField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string dds_fichaFieldField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string dds_inicioFieldField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string dds_licencFieldField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string dds_nacionFieldField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string dds_nfolioFieldField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string dds_nomcomFieldField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string dds_nrodocFieldField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string dds_numfaxFieldField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string dds_numrucFieldField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string dds_orientFieldField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string dds_paispaFieldField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string dds_pasapoFieldField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string dds_patronFieldField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string dds_sexoFieldField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string dds_telef1FieldField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string dds_telef2FieldField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string dds_telef3FieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string dds_asientField {
            get {
                return this.dds_asientFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.dds_asientFieldField, value) != true)) {
                    this.dds_asientFieldField = value;
                    this.RaisePropertyChanged("dds_asientField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string dds_comextField {
            get {
                return this.dds_comextFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.dds_comextFieldField, value) != true)) {
                    this.dds_comextFieldField = value;
                    this.RaisePropertyChanged("dds_comextField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string dds_constiField {
            get {
                return this.dds_constiFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.dds_constiFieldField, value) != true)) {
                    this.dds_constiFieldField = value;
                    this.RaisePropertyChanged("dds_constiField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string dds_contabField {
            get {
                return this.dds_contabFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.dds_contabFieldField, value) != true)) {
                    this.dds_contabFieldField = value;
                    this.RaisePropertyChanged("dds_contabField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string dds_docideField {
            get {
                return this.dds_docideFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.dds_docideFieldField, value) != true)) {
                    this.dds_docideFieldField = value;
                    this.RaisePropertyChanged("dds_docideField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string dds_domiciField {
            get {
                return this.dds_domiciFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.dds_domiciFieldField, value) != true)) {
                    this.dds_domiciFieldField = value;
                    this.RaisePropertyChanged("dds_domiciField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string dds_facturField {
            get {
                return this.dds_facturFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.dds_facturFieldField, value) != true)) {
                    this.dds_facturFieldField = value;
                    this.RaisePropertyChanged("dds_facturField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string dds_fecactField {
            get {
                return this.dds_fecactFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.dds_fecactFieldField, value) != true)) {
                    this.dds_fecactFieldField = value;
                    this.RaisePropertyChanged("dds_fecactField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string dds_fecnacField {
            get {
                return this.dds_fecnacFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.dds_fecnacFieldField, value) != true)) {
                    this.dds_fecnacFieldField = value;
                    this.RaisePropertyChanged("dds_fecnacField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string dds_fichaField {
            get {
                return this.dds_fichaFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.dds_fichaFieldField, value) != true)) {
                    this.dds_fichaFieldField = value;
                    this.RaisePropertyChanged("dds_fichaField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string dds_inicioField {
            get {
                return this.dds_inicioFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.dds_inicioFieldField, value) != true)) {
                    this.dds_inicioFieldField = value;
                    this.RaisePropertyChanged("dds_inicioField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string dds_licencField {
            get {
                return this.dds_licencFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.dds_licencFieldField, value) != true)) {
                    this.dds_licencFieldField = value;
                    this.RaisePropertyChanged("dds_licencField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string dds_nacionField {
            get {
                return this.dds_nacionFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.dds_nacionFieldField, value) != true)) {
                    this.dds_nacionFieldField = value;
                    this.RaisePropertyChanged("dds_nacionField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string dds_nfolioField {
            get {
                return this.dds_nfolioFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.dds_nfolioFieldField, value) != true)) {
                    this.dds_nfolioFieldField = value;
                    this.RaisePropertyChanged("dds_nfolioField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string dds_nomcomField {
            get {
                return this.dds_nomcomFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.dds_nomcomFieldField, value) != true)) {
                    this.dds_nomcomFieldField = value;
                    this.RaisePropertyChanged("dds_nomcomField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string dds_nrodocField {
            get {
                return this.dds_nrodocFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.dds_nrodocFieldField, value) != true)) {
                    this.dds_nrodocFieldField = value;
                    this.RaisePropertyChanged("dds_nrodocField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string dds_numfaxField {
            get {
                return this.dds_numfaxFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.dds_numfaxFieldField, value) != true)) {
                    this.dds_numfaxFieldField = value;
                    this.RaisePropertyChanged("dds_numfaxField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string dds_numrucField {
            get {
                return this.dds_numrucFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.dds_numrucFieldField, value) != true)) {
                    this.dds_numrucFieldField = value;
                    this.RaisePropertyChanged("dds_numrucField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string dds_orientField {
            get {
                return this.dds_orientFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.dds_orientFieldField, value) != true)) {
                    this.dds_orientFieldField = value;
                    this.RaisePropertyChanged("dds_orientField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string dds_paispaField {
            get {
                return this.dds_paispaFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.dds_paispaFieldField, value) != true)) {
                    this.dds_paispaFieldField = value;
                    this.RaisePropertyChanged("dds_paispaField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string dds_pasapoField {
            get {
                return this.dds_pasapoFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.dds_pasapoFieldField, value) != true)) {
                    this.dds_pasapoFieldField = value;
                    this.RaisePropertyChanged("dds_pasapoField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string dds_patronField {
            get {
                return this.dds_patronFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.dds_patronFieldField, value) != true)) {
                    this.dds_patronFieldField = value;
                    this.RaisePropertyChanged("dds_patronField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string dds_sexoField {
            get {
                return this.dds_sexoFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.dds_sexoFieldField, value) != true)) {
                    this.dds_sexoFieldField = value;
                    this.RaisePropertyChanged("dds_sexoField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string dds_telef1Field {
            get {
                return this.dds_telef1FieldField;
            }
            set {
                if ((object.ReferenceEquals(this.dds_telef1FieldField, value) != true)) {
                    this.dds_telef1FieldField = value;
                    this.RaisePropertyChanged("dds_telef1Field");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string dds_telef2Field {
            get {
                return this.dds_telef2FieldField;
            }
            set {
                if ((object.ReferenceEquals(this.dds_telef2FieldField, value) != true)) {
                    this.dds_telef2FieldField = value;
                    this.RaisePropertyChanged("dds_telef2Field");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string dds_telef3Field {
            get {
                return this.dds_telef3FieldField;
            }
            set {
                if ((object.ReferenceEquals(this.dds_telef3FieldField, value) != true)) {
                    this.dds_telef3FieldField = value;
                    this.RaisePropertyChanged("dds_telef3Field");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DatosEstablecimientoAnexo", Namespace="http://schemas.datacontract.org/2004/07/WCFSistemasService")]
    [System.SerializableAttribute()]
    public partial class DatosEstablecimientoAnexo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int spr_correlFieldField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string spr_fecactFieldField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string spr_inter1FieldField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string spr_licencFieldField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string spr_nombreFieldField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string spr_nomviaFieldField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string spr_nomzonFieldField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string spr_numer1FieldField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string spr_numrucFieldField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string spr_refer1FieldField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string spr_tipestFieldField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string spr_tipviaFieldField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string spr_tipzonFieldField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string spr_ubigeoFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int spr_correlField {
            get {
                return this.spr_correlFieldField;
            }
            set {
                if ((this.spr_correlFieldField.Equals(value) != true)) {
                    this.spr_correlFieldField = value;
                    this.RaisePropertyChanged("spr_correlField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string spr_fecactField {
            get {
                return this.spr_fecactFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.spr_fecactFieldField, value) != true)) {
                    this.spr_fecactFieldField = value;
                    this.RaisePropertyChanged("spr_fecactField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string spr_inter1Field {
            get {
                return this.spr_inter1FieldField;
            }
            set {
                if ((object.ReferenceEquals(this.spr_inter1FieldField, value) != true)) {
                    this.spr_inter1FieldField = value;
                    this.RaisePropertyChanged("spr_inter1Field");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string spr_licencField {
            get {
                return this.spr_licencFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.spr_licencFieldField, value) != true)) {
                    this.spr_licencFieldField = value;
                    this.RaisePropertyChanged("spr_licencField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string spr_nombreField {
            get {
                return this.spr_nombreFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.spr_nombreFieldField, value) != true)) {
                    this.spr_nombreFieldField = value;
                    this.RaisePropertyChanged("spr_nombreField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string spr_nomviaField {
            get {
                return this.spr_nomviaFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.spr_nomviaFieldField, value) != true)) {
                    this.spr_nomviaFieldField = value;
                    this.RaisePropertyChanged("spr_nomviaField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string spr_nomzonField {
            get {
                return this.spr_nomzonFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.spr_nomzonFieldField, value) != true)) {
                    this.spr_nomzonFieldField = value;
                    this.RaisePropertyChanged("spr_nomzonField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string spr_numer1Field {
            get {
                return this.spr_numer1FieldField;
            }
            set {
                if ((object.ReferenceEquals(this.spr_numer1FieldField, value) != true)) {
                    this.spr_numer1FieldField = value;
                    this.RaisePropertyChanged("spr_numer1Field");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string spr_numrucField {
            get {
                return this.spr_numrucFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.spr_numrucFieldField, value) != true)) {
                    this.spr_numrucFieldField = value;
                    this.RaisePropertyChanged("spr_numrucField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string spr_refer1Field {
            get {
                return this.spr_refer1FieldField;
            }
            set {
                if ((object.ReferenceEquals(this.spr_refer1FieldField, value) != true)) {
                    this.spr_refer1FieldField = value;
                    this.RaisePropertyChanged("spr_refer1Field");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string spr_tipestField {
            get {
                return this.spr_tipestFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.spr_tipestFieldField, value) != true)) {
                    this.spr_tipestFieldField = value;
                    this.RaisePropertyChanged("spr_tipestField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string spr_tipviaField {
            get {
                return this.spr_tipviaFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.spr_tipviaFieldField, value) != true)) {
                    this.spr_tipviaFieldField = value;
                    this.RaisePropertyChanged("spr_tipviaField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string spr_tipzonField {
            get {
                return this.spr_tipzonFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.spr_tipzonFieldField, value) != true)) {
                    this.spr_tipzonFieldField = value;
                    this.RaisePropertyChanged("spr_tipzonField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string spr_ubigeoField {
            get {
                return this.spr_ubigeoFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.spr_ubigeoFieldField, value) != true)) {
                    this.spr_ubigeoFieldField = value;
                    this.RaisePropertyChanged("spr_ubigeoField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ListarRepLegales", Namespace="http://schemas.datacontract.org/2004/07/WCFSistemasService")]
    [System.SerializableAttribute()]
    public partial class ListarRepLegales : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short num_ord_suceFieldField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string rso_cargooFieldField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string rso_docideFieldField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string rso_fecactFieldField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string rso_fecnacFieldField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string rso_nombreFieldField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string rso_nrodocFieldField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string rso_numrucFieldField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string rso_vdesdeFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short num_ord_suceField {
            get {
                return this.num_ord_suceFieldField;
            }
            set {
                if ((this.num_ord_suceFieldField.Equals(value) != true)) {
                    this.num_ord_suceFieldField = value;
                    this.RaisePropertyChanged("num_ord_suceField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string rso_cargooField {
            get {
                return this.rso_cargooFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.rso_cargooFieldField, value) != true)) {
                    this.rso_cargooFieldField = value;
                    this.RaisePropertyChanged("rso_cargooField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string rso_docideField {
            get {
                return this.rso_docideFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.rso_docideFieldField, value) != true)) {
                    this.rso_docideFieldField = value;
                    this.RaisePropertyChanged("rso_docideField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string rso_fecactField {
            get {
                return this.rso_fecactFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.rso_fecactFieldField, value) != true)) {
                    this.rso_fecactFieldField = value;
                    this.RaisePropertyChanged("rso_fecactField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string rso_fecnacField {
            get {
                return this.rso_fecnacFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.rso_fecnacFieldField, value) != true)) {
                    this.rso_fecnacFieldField = value;
                    this.RaisePropertyChanged("rso_fecnacField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string rso_nombreField {
            get {
                return this.rso_nombreFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.rso_nombreFieldField, value) != true)) {
                    this.rso_nombreFieldField = value;
                    this.RaisePropertyChanged("rso_nombreField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string rso_nrodocField {
            get {
                return this.rso_nrodocFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.rso_nrodocFieldField, value) != true)) {
                    this.rso_nrodocFieldField = value;
                    this.RaisePropertyChanged("rso_nrodocField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string rso_numrucField {
            get {
                return this.rso_numrucFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.rso_numrucFieldField, value) != true)) {
                    this.rso_numrucFieldField = value;
                    this.RaisePropertyChanged("rso_numrucField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string rso_vdesdeField {
            get {
                return this.rso_vdesdeFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.rso_vdesdeFieldField, value) != true)) {
                    this.rso_vdesdeFieldField = value;
                    this.RaisePropertyChanged("rso_vdesdeField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmpresaResponse", Namespace="http://schemas.datacontract.org/2004/07/Produce.AccesoalSistema.WCF")]
    [System.SerializableAttribute()]
    public partial class EmpresaResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PROCJUD.Web.ServiceSunat.DireccionResponse DireccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdPersonaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RazonSocialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RucField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PROCJUD.Web.ServiceSunat.DireccionResponse Direccion {
            get {
                return this.DireccionField;
            }
            set {
                if ((object.ReferenceEquals(this.DireccionField, value) != true)) {
                    this.DireccionField = value;
                    this.RaisePropertyChanged("Direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdPersona {
            get {
                return this.IdPersonaField;
            }
            set {
                if ((this.IdPersonaField.Equals(value) != true)) {
                    this.IdPersonaField = value;
                    this.RaisePropertyChanged("IdPersona");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RazonSocial {
            get {
                return this.RazonSocialField;
            }
            set {
                if ((object.ReferenceEquals(this.RazonSocialField, value) != true)) {
                    this.RazonSocialField = value;
                    this.RaisePropertyChanged("RazonSocial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ruc {
            get {
                return this.RucField;
            }
            set {
                if ((object.ReferenceEquals(this.RucField, value) != true)) {
                    this.RucField = value;
                    this.RaisePropertyChanged("Ruc");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DireccionResponse", Namespace="http://schemas.datacontract.org/2004/07/Produce.AccesoalSistema.WCF")]
    [System.SerializableAttribute()]
    public partial class DireccionResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodDepartamentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodDistritoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodProvinciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DirecField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodDepartamento {
            get {
                return this.CodDepartamentoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodDepartamentoField, value) != true)) {
                    this.CodDepartamentoField = value;
                    this.RaisePropertyChanged("CodDepartamento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodDistrito {
            get {
                return this.CodDistritoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodDistritoField, value) != true)) {
                    this.CodDistritoField = value;
                    this.RaisePropertyChanged("CodDistrito");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodProvincia {
            get {
                return this.CodProvinciaField;
            }
            set {
                if ((object.ReferenceEquals(this.CodProvinciaField, value) != true)) {
                    this.CodProvinciaField = value;
                    this.RaisePropertyChanged("CodProvincia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Direc {
            get {
                return this.DirecField;
            }
            set {
                if ((object.ReferenceEquals(this.DirecField, value) != true)) {
                    this.DirecField = value;
                    this.RaisePropertyChanged("Direc");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceSunat.IWCFSistemasService")]
    public interface IWCFSistemasService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFSistemasService/BuscarSunatProduccionParametro", ReplyAction="http://tempuri.org/IWCFSistemasService/BuscarSunatProduccionParametroResponse")]
        PROCJUD.Web.ServiceSunat.BuscarEmpresaResult BuscarSunatProduccionParametro(string ID_RUC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFSistemasService/BuscarSunatProduccionParametro", ReplyAction="http://tempuri.org/IWCFSistemasService/BuscarSunatProduccionParametroResponse")]
        System.Threading.Tasks.Task<PROCJUD.Web.ServiceSunat.BuscarEmpresaResult> BuscarSunatProduccionParametroAsync(string ID_RUC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFSistemasService/Validacion_SUNAT", ReplyAction="http://tempuri.org/IWCFSistemasService/Validacion_SUNATResponse")]
        PROCJUD.Web.ServiceSunat.BuscarEmpresaResult Validacion_SUNAT(string ID_RUC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFSistemasService/Validacion_SUNAT", ReplyAction="http://tempuri.org/IWCFSistemasService/Validacion_SUNATResponse")]
        System.Threading.Tasks.Task<PROCJUD.Web.ServiceSunat.BuscarEmpresaResult> Validacion_SUNATAsync(string ID_RUC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFSistemasService/Validacion_OGACI", ReplyAction="http://tempuri.org/IWCFSistemasService/Validacion_OGACIResponse")]
        PROCJUD.Web.ServiceSunat.BuscarEmpresaResult Validacion_OGACI(string ID_RUC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFSistemasService/Validacion_OGACI", ReplyAction="http://tempuri.org/IWCFSistemasService/Validacion_OGACIResponse")]
        System.Threading.Tasks.Task<PROCJUD.Web.ServiceSunat.BuscarEmpresaResult> Validacion_OGACIAsync(string ID_RUC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFSistemasService/Persona_Juridica_Sunat", ReplyAction="http://tempuri.org/IWCFSistemasService/Persona_Juridica_SunatResponse")]
        PROCJUD.Web.ServiceSunat.EmpresaResponse Persona_Juridica_Sunat(string ruc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFSistemasService/Persona_Juridica_Sunat", ReplyAction="http://tempuri.org/IWCFSistemasService/Persona_Juridica_SunatResponse")]
        System.Threading.Tasks.Task<PROCJUD.Web.ServiceSunat.EmpresaResponse> Persona_Juridica_SunatAsync(string ruc);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWCFSistemasServiceChannel : PROCJUD.Web.ServiceSunat.IWCFSistemasService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WCFSistemasServiceClient : System.ServiceModel.ClientBase<PROCJUD.Web.ServiceSunat.IWCFSistemasService>, PROCJUD.Web.ServiceSunat.IWCFSistemasService {
        
        public WCFSistemasServiceClient() {
        }
        
        public WCFSistemasServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WCFSistemasServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WCFSistemasServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WCFSistemasServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public PROCJUD.Web.ServiceSunat.BuscarEmpresaResult BuscarSunatProduccionParametro(string ID_RUC) {
            return base.Channel.BuscarSunatProduccionParametro(ID_RUC);
        }
        
        public System.Threading.Tasks.Task<PROCJUD.Web.ServiceSunat.BuscarEmpresaResult> BuscarSunatProduccionParametroAsync(string ID_RUC) {
            return base.Channel.BuscarSunatProduccionParametroAsync(ID_RUC);
        }
        
        public PROCJUD.Web.ServiceSunat.BuscarEmpresaResult Validacion_SUNAT(string ID_RUC) {
            return base.Channel.Validacion_SUNAT(ID_RUC);
        }
        
        public System.Threading.Tasks.Task<PROCJUD.Web.ServiceSunat.BuscarEmpresaResult> Validacion_SUNATAsync(string ID_RUC) {
            return base.Channel.Validacion_SUNATAsync(ID_RUC);
        }
        
        public PROCJUD.Web.ServiceSunat.BuscarEmpresaResult Validacion_OGACI(string ID_RUC) {
            return base.Channel.Validacion_OGACI(ID_RUC);
        }
        
        public System.Threading.Tasks.Task<PROCJUD.Web.ServiceSunat.BuscarEmpresaResult> Validacion_OGACIAsync(string ID_RUC) {
            return base.Channel.Validacion_OGACIAsync(ID_RUC);
        }
        
        public PROCJUD.Web.ServiceSunat.EmpresaResponse Persona_Juridica_Sunat(string ruc) {
            return base.Channel.Persona_Juridica_Sunat(ruc);
        }
        
        public System.Threading.Tasks.Task<PROCJUD.Web.ServiceSunat.EmpresaResponse> Persona_Juridica_SunatAsync(string ruc) {
            return base.Channel.Persona_Juridica_SunatAsync(ruc);
        }
    }
}
